In [1]:
!pip install gymnasium renderlab

In [2]:
!pip install opencv-python

In [3]:
import gymnasium as gym

In [22]:
desc=["SFFF", "FHHH", "FFFF", "HFHF", "FFGF"]

env = gym.make('FrozenLake-v1', desc=desc, map_name="5x5", is_slippery=False, render_mode="human") 
observation, info = env.reset()

In [9]:
import numpy as np

# Define the number of states and actions
num_states = 19
num_actions = 4

# Initialize the Q-table with zeros
Q_table = np.zeros((num_states, num_actions))

print(Q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
env.step(0)#left

(0, 0.0, False, False, {'prob': 1.0})

In [16]:
env.step(1)#Down

(17, 0.0, False, False, {'prob': 1.0})

In [17]:
env.step(2)#right

(18, 1.0, True, False, {'prob': 1.0})

In [19]:
env.step(3)#up

(18, 0, True, False, {'prob': 1.0})

In [20]:
obserbation, info = env.reset()

In [21]:
env.close()

In [23]:
alpha = 0.7
gamma = 0.7
epsilon = 0.5
episodeMax = 10